# parse_data.ipynb

This notebook parses the data files used for the FP-2 assignment.

<br>
<br>

First let's read the attached data file:

In [1]:
import pandas as pd

df0 = pd.read_csv('Earthquakes.csv')

df0.describe()

,Unnamed: 0,Year,Mo,Dy,Hr,Mn,Sec,Tsu,Vol,Latitude,...,Total Missing,Total Missing Description,Total Injuries,Total Injuries Description,Total Damage ($Mil),Total Damage Description,Total Houses Destroyed,Total Houses Destroyed Description,Total Houses Damaged,Total Houses Damaged Description
count,0.0,2207.000000,2155.000000,2118.000000,1663.000000,1605.000000,1423.00000,574.000000,17.000000,2200.000000,...,26.000000,30.000000,981.000000,1165.000000,473.000000,2182.000000,6.420000e+02,1347.000000,3.170000e+02,556.000000
mean,NaN,1851.187585,6.486311,15.881492,11.429345,28.907788,28.96929,2507.097561,3021.117647,22.295058,...,197.307692,1.866667,3411.295617,2.252361,2043.582085,2.604033,2.510023e+04,2.930215,8.930264e+04,2.937050
std,NaN,306.129372,3.434785,8.586146,7.022803,17.326560,17.89336,1817.930854,1984.402929,20.210734,...,392.594729,1.074255,31447.741490,1.105984,12421.094317,0.993764,2.215781e+05,0.999049,1.182125e+06,1.099383
min,NaN,-2000.000000,1.000000,1.000000,0.000000,0.000000,0.00000,10.000000,1.000000,-54.000000,...,1.000000,1.000000,1.000000,1.000000,0.100000,1.000000,1.000000e+00,1.000000,2.000000e+00,1.000000
25%,NaN,1850.500000,4.000000,9.000000,5.000000,14.000000,13.15000,1140.000000,867.000000,10.659250,...,3.500000,1.000000,22.000000,1.000000,5.000000,2.000000,1.600000e+02,2.000000,3.400000e+02,2.000000
50%,NaN,1956.000000,7.000000,16.000000,11.000000,29.000000,29.20000,2061.500000,3551.000000,29.752000,...,25.500000,1.000000,100.000000,2.000000,43.000000,3.000000,1.000000e+03,3.000000,1.678000e+03,3.000000
75%,NaN,1998.000000,9.000000,23.000000,18.000000,44.000000,45.00000,3492.250000,4512.000000,37.684000,...,132.500000,3.000000,400.000000,3.000000,400.000000,3.000000,5.914000e+03,4.000000,8.057000e+03,4.000000
max,NaN,2025.000000,12.000000,31.000000,23.000000,59.000000,59.90000,6050.000000,6624.000000,60.908000,...,1755.000000,4.000000,799000.000000,4.000000,220136.600000,4.000000,5.360000e+06,4.000000,2.100000e+07,4.000000

<br>
<br>

The dependent and independent variables variables (DVs and IVs) that we are interested in are:

**DVs**:
- Death Description

**IVs**:
Mag (magnitude), Focal Depth (km) (depth of earthquake focus in kilometers), Latitude (geographic latitude), Longitude (geographic longitude)


<br>
<br>

Let's extract the relevant columns:

In [2]:
df = df0[['Death Description', 'Mag', 'Focal Depth (km)', 'Latitude', 'Longitude']]
df = df.dropna(subset=["Death Description", "Mag", "Focal Depth (km)", "Latitude", "Longitude"])
df.describe()

,Death Description,Mag,Focal Depth (km),Latitude,Longitude
count,1348.000000,1348.000000,1348.000000,1348.000000,1348.000000
mean,1.612018,6.421958,30.352374,18.832711,35.772519
std,1.033976,0.964511,38.804668,21.297995,80.757761
min,1.000000,2.100000,0.000000,-54.000000,-178.252000
25%,1.000000,5.800000,10.000000,1.100000,-66.803250
50%,1.000000,6.400000,20.000000,25.324500,52.033500
75%,2.000000,7.100000,33.000000,36.802000,102.740750
max,4.000000,9.500000,651.000000,60.908000,178.291000

<br>
<br>

Next let's use the `rename` function to give the columns simpler variable names:

In [3]:
df = df.rename( columns={'Focal Depth (km)':'Focal Depth', 'Latitude':'Lat', 'Longitude':'Long'} )

df.describe()

       Death Description          Mag  Focal Depth          Lat         Long
count        1348.000000  1348.000000  1348.000000  1348.000000  1348.000000
mean            1.612018     6.421958    30.352374    18.832711    35.772519
std             1.033976     0.964511    38.804668    21.297995    80.757761
min             1.000000     2.100000     0.000000   -54.000000  -178.252000
25%             1.000000     5.800000    10.000000     1.100000   -66.803250
50%             1.000000     6.400000    20.000000    25.324500    52.033500
75%             2.000000     7.100000    33.000000    36.802000   102.740750
max             4.000000     9.500000   651.000000    60.908000   178.291000